<div class="main-content-home">
    <div class="main-banner">
        <div class="main-banner-img">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-image')->toHtml() ?>
        </div>
        <div class="main-banner-content">
            <div class="main-banner-main-text">
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-main-text')->toHtml() ?>
            </div>
            <div class="main-banner-extra-text">
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-extra-text')->toHtml() ?>
            </div>
            <button class="action main-banner-btn" type="submit">
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-btn')->toHtml() ?>
            </button>
        </div>
    </div>
    <div class="extra-banner">
        <div class="custom-container">
            <div class="extra-banner-content">
                <?php for ($i = 1; $i <= 3; $i++) { ?>
                    <div class="extra-banner-item">
                        <div class="extra-banner-img">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extra-banner-image-' . $i)->toHtml() ?>
                        </div>
                        <div class="extra-banner-text">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extra-banner-text-' . $i)->toHtml() ?>
                        </div>
                    </div>
                <?php } ?>
                <div class="extra-banner-item mobile">
                    <div class="extra-banner-img">
                        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extra-banner-image-4')->toHtml() ?>
                    </div>
                    <div class="extra-banner-text">
                        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extra-banner-text-4')->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ingredient">
        <div class="ingredient-title">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ingredient-title')->toHtml() ?>
        </div>
        <div class="ingredient-des">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ingredient-des')->toHtml() ?>
        </div>
        <ul class="ingredient-list">
            <?php for ($i = 1; $i <= 16; $i++) { ?>
                <li class="ingredient-item">
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ingredient-icon-' . $i)->toHtml() ?>
                </li>
            <?php } ?>
        </ul>
        <button class="action primary ingredient-btn" type="submit">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ingredient-btn')->toHtml() ?>
        </button>
    </div>
    <div class="best-seller">
        <div class="best-seller-list">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bestseller')->toHtml() ?>
        </div>
    </div>
    <div class="shop-contact">
        <div class="shop-contact-title">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop-contact-title')->toHtml() ?>
        </div>
        <div class="shop-contact-des">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop-contact-des')->toHtml() ?>
            <i class="lab la-instagram"></i>
        </div>
        <ul class="shop-contact-list">
            <?php for ($i = 1; $i <= 8; $i++) { ?>
                <li class="shop-contact-item">
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop-contact-img-' . $i)->toHtml() ?>
                </li>
            <?php } ?>
        </ul>
        <button class="action primary shop-contact-btn" type="submit">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop-contact-btn')->toHtml() ?>
        </button>
    </div>
</div>
<script>
require(['jquery', 'slick'], function($) {
    $(document).ready(function() {
        $(".product-items").slick({
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            swipeToSlide: true,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                        infinite: true,
                        dots: false,
                    }
                },
                {
                    breakpoint: 640,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        arrows: false,
                        dots: false,
                    }
                },
                {
                    breakpoint: 320,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        arrows: false,
                        dots: false,
                    }
                }
            ]
        });
    });
});
</script>